# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a15tcpg236-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mistrz/Desktop/inz/projekt_vivado/projekt_vivado.cache/wt [current_project]
set_property parent.project_path /home/mistrz/Desktop/inz/projekt_vivado/projekt_vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/mistrz/Desktop/inz/rtl/usbf_defines.v
  /home/mistrz/Desktop/inz/rtl/usbf_crc16.v
  /home/mistrz/Desktop/inz/rtl/usbf_crc5.v
  /home/mistrz/Desktop/inz/rtl/usbf_utmi_ls.v
  /home/mistrz/Desktop/inz/rtl/usbf_ep_rf.v
  /home/mistrz/Desktop/inz/rtl/usbf_ep_rf_dummy.v
  /home/mistrz/Desktop/inz/rtl/usbf_idma.v
  /home/mistrz/Desktop/inz/rtl/usbf_pa.v
  /home/mistrz/Desktop/inz/rtl/usbf_pd.v
  /home/mistrz/Desktop/inz/rtl/usbf_pe.v
  /home/mistrz/Desktop/inz/rtl/usbf_pl.v
  /home/mistrz/Desktop/inz/rtl/usbf_wb.v
  /home/mistrz/Desktop/inz/rtl/usbf_rf.v
  /home/mistrz/Desktop/inz/rtl/usbf_utmi_if.v
  /home/mistrz/Desktop/inz/rtl/usbf_mem_arb.v
  /home/mistrz/Desktop/inz/rtl/sram.v
  /home/mistrz/Desktop/inz/rtl/usbf_top.v
}
synth_design -top usbf_top -part xc7a15tcpg236-3
write_checkpoint -noxdef usbf_top.dcp
catch { report_utilization -file usbf_top_utilization_synth.rpt -pb usbf_top_utilization_synth.pb }
